# NUMPY

In [2]:
import numpy as np

In [3]:
vec=[1,2,3]

In [4]:
np_vec=np.array(vec)
print(np_vec)

[1 2 3]


In [5]:
mat=[[2,3,4],[3,4,5]]
np_mat=(np.array(mat))
print(np_mat)

[[2 3 4]
 [3 4 5]]


In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.random.randn(3,5)

array([[ 0.04108548, -1.49389376,  0.47632288, -0.67212422,  0.30748684],
       [ 0.9134692 , -0.83312655,  0.89225908,  0.2384066 , -0.91291888],
       [ 0.16288873, -0.22737412,  0.81633525,  0.80156881, -0.06866751]])

In [10]:
np.random.randint(5,15,6)

array([13,  9,  8, 14, 13, 14])

In [11]:
np.arange(4,9,3)

array([4, 7])

In [12]:
np.linspace(2,13,5)

array([ 2.  ,  4.75,  7.5 , 10.25, 13.  ])

In [13]:
np_mat.shape

(2, 3)

In [14]:
np_mat.min()

2

In [15]:
np_mat.reshape(3,2)

array([[2, 3],
       [4, 3],
       [4, 5]])

# Create numpy array which has all number divisible by 3 between 10 and 100.

In [17]:
arr1=np.arange(10,100)
ans=(arr1[(arr1%3==0)])
print(ans)
print(type(ans))

[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]
<class 'numpy.ndarray'>


# Find Second largest value in above array.

In [18]:
ans.sort()
print(ans[-2])

96


In [19]:
n=np.random.randint(10,100,60)
print(n)
n.sort()
print(n)
print(n[-3])


[47 83 47 42 71 82 53 15 38 81 97 25 24 82 14 64 56 71 81 69 88 69 73 65
 34 88 22 74 89 10 33 78 90 80 26 62 29 29 34 99 26 49 39 80 51 55 41 68
 79 22 69 50 26 80 15 97 88 20 25 50]
[10 14 15 15 20 22 22 24 25 25 26 26 26 29 29 33 34 34 38 39 41 42 47 47
 49 50 50 51 53 55 56 62 64 65 68 69 69 69 71 71 73 74 78 79 80 80 80 81
 81 82 82 83 88 88 88 89 90 97 97 99]
97
